### ISSUE TITLE
Mac libdb2.dylib image not found

### ISSUE THREAD

**Issue by dat2** [ibmdb/python-ibmdb#187]
```
>>> import ibm_db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/usr/local/lib/python3.5/site-packages/ibm_db.cpython-35m-darwin.so, 2): Library not loaded: libdb2.dylib
  Referenced from: /usr/local/lib/python3.5/site-packages/ibm_db.cpython-35m-darwin.so
  Reason: image not found
```

This issue can be solved by running
```bash
cd /usr/local/lib/python3.5/site-packages
install_name_tool -change libdb2.dylib `pwd`/libdb2.dylib ibm_db.cpython-35m-darwin.so
```
http://thecourtsofchaos.com/2013/09/16/how-to-copy-and-relink-binaries-on-osx/

However, this needs to be run after pip compiles it. 
http://stackoverflow.com/questions/1321270/how-to-extend-distutils-with-a-simple-post-install-script

**Comment by kdazzle** [comment]
I'm seeing this issue, too. Django 1.9, python 2.7

**Comment by IBMAmarPY** [comment]
Above problem and solution is discussed in the following blog, please follow the #2 in blog:
https://www.ibm.com/developerworks/community/blogs/96960515-2ea1-4391-8170-b0515d08e4da/entry/ibm_db_on_MAC_OS_Hints_and_Tips?lang=en

**Comment by kdazzle** [comment]
Thanks for the response! Yeah I saw that workaround - I thought this issue might have been closed because it had been fixed. I'll submit a PR to add that process to the docs so it isn't buried in a closed issue.

**Comment by genomics-geek** [comment]
I used this and it fixed my import issue. However when I try to connect I get the following error:

```
import ibm_db
ibm_db.connect("DATABASE=BIGSQL;HOSTNAME=HOST;PORT=32051;PROTOCOL=TCPIP;UID=UID;PWD=PWD;", "", "")
Exception: [IBM][CLI Driver] SQL10007N Message "0" could not be retrieved.  Reason code: "3". SQLCODE=-1042
```

**Comment by genomics-geek** [comment]
I fixed the the Exception by adding: `AUTHENTICATION=SERVER`.

```python
conn = ibm_db.connect("DATABASE=BIGSQL;HOSTNAME=mn0204.chop.edu;PORT=32051;PROTOCOL=TCPIP;UID=gonzalezma;PWD=removed;AUTHENTICATION=SERVER", "", "")
```

However now in ibm_db_django I get the same error as above. I need to find out how to pass `AUTHENTICATION=SERVER` to the connection.

**Comment by IBMAmarPY** [comment]
I will get back to you on this soon

-Amar

**Comment by Vyshakh18** [comment]
Hi,
Could you try using db2dsdriver.cfg file and mention the value of AUTHENTICATION parameter as SERVER for the DB which you are using?
A screenshot of a sample db2dsdriver.cfg file is attached here:
![capture](https://cloud.githubusercontent.com/assets/20924484/23509487/fe09119c-ff7b-11e6-9548-3c4a15a45530.JPG)


For more info regarding db2dsdriver.cfg, please refer to:
https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.swg.im.dbclient.config.doc/doc/c0054555.html

For info regarding the location of db2dsdriver.cfg, please follow the below link:
https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.swg.im.dbclient.config.doc/doc/r0061058.html

**Comment by theodoretliu** [comment]
Hey, I've been experiencing the same problem that initially started the thread. I tried the solution described in this issue, but it did not fix my problem. I'm using a virtual environment, but even when I deactivated it and installed globally, the problem persists. I'm using Python 3.6

**Comment by genomics-geek** [comment]
@theodoretliu are you on a Mac?

**Comment by theodoretliu** [comment]
Yeah, I'm on a Mac

**Comment by genomics-geek** [comment]
This is what helped me:

```
cd /Users/gonzalezma/.pyenv/versions/3.5.2/envs/django-ibm/lib/python3.5/site-packages
install_name_tool -change libdb2.dylib `pwd`/libdb2.dylib ibm_db.cpython-35m-darwin.so
ln -s clidriver/lib/libdb2.dylib libdb2.dylib
```

Change the path to your site-packages for your environment

**Comment by theodoretliu** [comment]
Oh, awesome. Where did you find the symlink stuff?

**Comment by genomics-geek** [comment]
@theodoretliu not sure to be honest lol  I think I noticed that the `libdb2.dylib` didn't exist so I created a symlink and then it worked.

**Comment by genomics-geek** [comment]
@theodoretliu did it work?

**Comment by theodoretliu** [comment]
@genomics-geek You are absolutely awesome. This gave me grief for 6 hours+. Yes!

**Comment by theodoretliu** [comment]
@genomics-geek Did adding "AUTHENTICATION=SERVER" fully resolve `Message "0" could not be receive` error?

**Comment by genomics-geek** [comment]
Yup that resolved my issue for me.

**Comment by theodoretliu** [comment]
@genomics-geek thanks for all your help!

**Comment by brityboy** [comment]
My approach in fixing this was to add this to my bash profile:
```
export DYLD_LIBRARY_PATH="/anaconda/lib/python2.7/site-packages/clidriver/lib:$DYLD_LIBRARY_PATH"
```

I did this after identifying where `libdb2.dylib` was located which I did on my mac by doing the ff steps:
1. command + space
2. type `libdb2.dylib
3. hit enter and see this
```
/anaconda/lib/python2.7/site-packages/clidriver/lib/libdb2.dylib
```

Reactivate the bash profile with `source ~/.bash_profile` and voila, problem solved

using python 2.7.13

**Comment by ValkA** [comment]
if you dont want to alter your bash_profile then you can add this

`
DYLD_LIBRARY_PATH="$VIRTUAL_ENV/lib/python3.6/site-packages/clidriver/lib/icc"
export DYLD_LIBRARY_PATH
`

to ./venv/bin/activate.

**Comment by digglife** [comment]
@genomics-geek 

The link command is required for my case. Thank you!

**Comment by lauksas** [comment]
I was having the same error and found that the installDSDriver script creates a file at /Applications/dsdriver/db2profile stating the below:
```bash
# NAME:     db2profile
#
# FUNCTION: This script sets up a default database environment for
#           Bourne shell or Korn shell users.
#
#           This file is tuned for IBM Data Server Driver Package only.
#
# USAGE:    . db2profile
#           This script can either be invoked directly as above or
#           it can be added to the user's .profile file so that the
#           database environment is established during login.
#
```

so I just added on my ~/.bash_profile the line below:

`source /Applications/dsdriver/db2profile`

Open a new terminal window or restart your mac and should work.
This file exports all the environment variables needed for the db2cli command to work.
