### ISSUE TITLE
Getting incorrect datetime results in SQL calls

### ISSUE THREAD

**Issue by tuchfarber** [ibmdb/python-ibmdb#253]
When retrieving items using SQL, the columns that hold a timestamp are returning invalid datetime objects. I'm calling this code through an interactive Python 3 prompt in QSH. 

See the following code :
```
Python 3.4.4 (default, Mar 23 2016, 11:07:11)                         
[GCC 4.8.4] on aix6                                                   
Type "help", "copyright", "credits" or "license" for more information.
>>>
import ibm_db
>>>
db_name = '*LOCAL'
>>>
SQL_ATTR_DBC_SYS_NAMING = 10004
>>>
conn = ibm_db.connect(db_name, None, None, {SQL_ATTR_DBC_SYS_NAMING: ibm_db.SQL_TRUE})
>>>
sql = "SELECT QL5PONB, QL5MNTD FROM HQPGMXT.EQULST5P WHERE QL5PONB='1148083'"
>>>
result_set = ibm_db.exec_immediate(conn,sql)
>>>
ibm_db.fetch_assoc(result_set)
{'QL5MNTD': datetime.datetime(1208, 81, 3, 0, 0, 40, 79008), 'QL5PONB': '1148083             '}
>>>
result_set = ibm_db.exec_immediate(conn,sql)
>>>
ibm_db.fetch_assoc(result_set)
{'QL5MNTD': datetime.datetime(530, 0, 3, 0, 0, 40, 79008), 'QL5PONB': '1148083             '}
>>>
result_set = ibm_db.exec_immediate(conn,sql)
>>>
ibm_db.fetch_assoc(result_set)
{'QL5MNTD': datetime.datetime(840, 0, 3, 0, 0, 40, 79008), 'QL5PONB': '1148083             '}
>>>
result_set = ibm_db.exec_immediate(conn,sql)
>>>
ibm_db.fetch_assoc(result_set)
{'QL5MNTD': datetime.datetime(1208, 81, 3, 0, 0), 'QL5PONB': '1148083             '}
>>>
```
For reference, here is the same query being ran thought the "Run SQL Scripts" utility:
![image](https://cloud.githubusercontent.com/assets/6179874/22307413/d89b6e0a-e310-11e6-90f0-838231143db5.png)

As you can see, when calling from Python, the datetime objects change every time I try to retrieve them. In addition, these datetime objects are invalid (e.g. months of 0 and 81). They also vary from 5 to 7 parameters in the examples I've ran (e.g. ```datetime.datetime(530, 0, 3, 0, 0, 40, 79008)``` vs ```datetime.datetime(1208, 81, 3, 0, 0)```) The date objects seem to be correct and consistant, but the datetimes are not. 

Any help would be greatly appreciated. Let me know if you need any more information. Thanks.

**Comment by kadler** [comment]
This should be fixed in the latest IBM i code, released with PTFs SI61963 (Python 3) and SI61964 (Python 2). Can you verify you're running ibm_db_dbi version 2.0.5.5?

```
python3 -c 'import ibm_db_dbi; print(ibm_db_dbi.__version__)'
```

**Comment by tuchfarber** [comment]
Thank you for your quick response! It seems as if we are currently running 2.0.5.4, so that is probably our issue. Since I'm not sure how quickly we'll be able to install them, I'll close the issue for now and will reopen if we still have issues after the update. Thanks for your help.
