### ISSUE TITLE
pip install --user ibm_db fails on Fedora 33 / python 3.9

### ISSUE THREAD

**Issue by jmcmeek** [ibmdb/python-ibmdb#596]
`pip install --user ibm_db` fails on my Fedora 33 system which has Python 3.9:
```
$ pip install --user ibm_db &>pip_install_ibm_db.log
....
    byte-compiling /home/jmcmeek/.local/lib/python3.9/site-packages/ibm_db_tests/test_trusted_context_pconnect.py to test_trusted_context_pconnect.cpython-39.pyc
    byte-compiling /home/jmcmeek/.local/lib/python3.9/site-packages/ibm_db_tests/test_warn.py to test_warn.cpython-39.pyc
    byte-compiling /home/jmcmeek/.local/lib/python3.9/site-packages/clidriver/__init__.py to __init__.cpython-39.pyc
    byte-compiling /home/jmcmeek/.local/lib/python3.9/site-packages/testfunctions.py to testfunctions.cpython-39.pyc
    byte-compiling /home/jmcmeek/.local/lib/python3.9/site-packages/ibm_db_dbi.py to ibm_db_dbi.cpython-39.pyc
    running install_data
    copying ./README.md -> /usr/lib/python3.9/site-packages
    error: could not create '/usr/lib/python3.9/site-packages/README.md': Permission denied
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uwac80di/ibm-db_0e95e67d3216437cb05c6dd570b38bdc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uwac80di/ibm-db_0e95e67d3216437cb05c6dd570b38bdc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-n7q75ojf/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/jmcmeek/.local/include/python3.9/ibm-db Check the logs for full command output.
```
```
$ pip --version
pip 21.0.1 from /home/jmcmeek/.local/lib/python3.9/site-packages/pip (python 3.9)
$ python --version
Python 3.9.1
```

**Comment by jmcmeek** [comment]
Full pip install log:
[pip_install_ibm_db.log.gz](https://github.com/ibmdb/python-ibmdb/files/5913774/pip_install_ibm_db.log.gz)

**Comment by amukherjee28** [comment]
Hi @jmcmeek 

From the error that you have pasted, could you please check your user permission on the below mentioned folder path.
'/usr/lib/python3.9/site-packages/README.md': Permission denied

pip install is trying to install the driver into the /usr/lib/python3.9/site-packages folder and looks like the user does not have access to the path and installation fails with Permission denied.

Please grant access to the path as any pip install will install packages in the same location.

Thanks

**Comment by jmcmeek** [comment]
@amukherjee28  Isn't a `--user` install supposed to install in my home directory - `/home/jmcmeek/.local/lib/python3.9/site-packages`?

Otherwise I think I'd have to do `sudo pip install`.  The last time I did that it caused problems with operating system managed package updates.

**Comment by jmcmeek** [comment]
ok, that was not as bad as I feared.
```
$ sudo chmod o+rwx /usr/lib/python3.9/site-packages/

$ pip install --user ibm_db
Collecting ibm_db
  Using cached ibm_db-3.0.3.tar.gz (794 kB)
Using legacy 'setup.py install' for ibm-db, since package 'wheel' is not installed.
Installing collected packages: ibm-db
    Running setup.py install for ibm-db ... done
Successfully installed ibm-db-3.0.3

$ ls -l /usr/lib/python3.9/site-packages/ | grep jmcmeek
-rwxrwxr-x.  1 jmcmeek jmcmeek  14238 Feb  1 14:38 CHANGES
-rwxrwxr-x.  1 jmcmeek jmcmeek   1463 Feb  1 04:34 config.py.sample
-rwxrwxr-x.  1 jmcmeek jmcmeek   9219 Jun 16  2020 LICENSE
-rwxrwxr-x.  1 jmcmeek jmcmeek   9827 Feb  1 14:36 README.md
```

I was afraid it was going to dump a lot more there.  Still, I don't think it should have put anything there.

**Comment by AWADHAMBIKA** [comment]
Hi @jmcmeek I hope your issue is resolved or you have any other queries? Can you close this issue if there are no additional queries?

**Comment by jmcmeek** [comment]
@AWADHAMBIKA Yes and no.

I have my system working.  However, my understanding is that other people installing the tool that pulls in ibm_db have encountered this issue.

While we have a work-around the problem remains that a `--user` install is putting those 4 files in `/usr/lib/python3.9/site-packages/` and that shouldn't be happening.  Those file should be going somewhere under `~/.local`.

**Comment by amukherjee28** [comment]
Hi @jmcmeek 

I replicated the scenario and the installation went fine into my user directory in windows.

C:\Users\amukherjee>pip uninstall ibm_db
Found existing installation: ibm-db 3.0.3
Uninstalling ibm-db-3.0.3:
  Would remove:
    c:\users\amukherjee\appdata\roaming\python\python39\site-packages\certs\*
    c:\users\amukherjee\appdata\roaming\python\python39\site-packages\clidriver\*
    c:\users\amukherjee\appdata\roaming\python\python39\site-packages\ibm_db-3.0.3-py3.9.egg-info
    c:\users\amukherjee\appdata\roaming\python\python39\site-packages\ibm_db.py
    c:\users\amukherjee\appdata\roaming\python\python39\site-packages\ibm_db_dbi.py
    c:\users\amukherjee\appdata\roaming\python\python39\site-packages\ibm_db_dlls\*
    c:\users\amukherjee\appdata\roaming\python\python39\site-packages\ibm_db_tests\*
    c:\users\amukherjee\appdata\roaming\python\python39\site-packages\testfunctions.py
    c:\users\amukherjee\appdata\roaming\python\python39\site-packages\tests.py
    c:\users\amukherjee\python391\lib\site-packages\changes
    c:\users\amukherjee\python391\lib\site-packages\config.py.sample
    c:\users\amukherjee\python391\lib\site-packages\license
    c:\users\amukherjee\python391\lib\site-packages\readme.md

I did some digging and looks like in Fedora the environment variable PATH is appending ~/.local/bin by default and hence the pip install --user goes to the same path.

This is a know issue with Fedora.

Please check the link below.

https://github.com/pypa/pip/issues/3813

Hope this resolves your problem.

Usually the pip install is controlled by the pypi package manager. From driver point of view we are not controlling the install location.

Thanks.

**Comment by jmcmeek** [comment]
```
$ pip uninstall ibm_db
Found existing installation: ibm-db 3.0.3
Uninstalling ibm-db-3.0.3:
  Would remove:
    /home/jmcmeek/.local/lib/python3.9/site-packages/certs/*
    /home/jmcmeek/.local/lib/python3.9/site-packages/clidriver/*
    /home/jmcmeek/.local/lib/python3.9/site-packages/ibm_db-3.0.3-py3.9.egg-info
    /home/jmcmeek/.local/lib/python3.9/site-packages/ibm_db.cpython-39-x86_64-linux-gnu.so
    /home/jmcmeek/.local/lib/python3.9/site-packages/ibm_db_dbi.py
    /home/jmcmeek/.local/lib/python3.9/site-packages/ibm_db_tests/*
    /home/jmcmeek/.local/lib/python3.9/site-packages/testfunctions.py
    /home/jmcmeek/.local/lib/python3.9/site-packages/tests.py
    /usr/lib/python3.9/site-packages/CHANGES
    /usr/lib/python3.9/site-packages/LICENSE
    /usr/lib/python3.9/site-packages/README.md
    /usr/lib/python3.9/site-packages/config.py.sample
```
Most of the files are where they should be - just those last 4 ended up in what seems like the wrong place.

I wonder if this is related:
https://github.com/ibmdb/python-ibmdb/blob/b74c94866c2e7707ef5a1bf3b199579a34633b69/IBM_DB/ibm_db/setup.py#L339-L342

**Comment by amukherjee28** [comment]
Hi @jmcmeek 

Looks like linux is playing around with the function call get_python_lib() based on the environment variable.

Let me do a bit more digging on this and I will get back to you.
In windows the behavior is smooth and works as expected.

In linux because of the file system there is some differences.

I will check on this a bit more.

Thanks.

**Comment by imavo** [comment]
I observe that pip versions above 21 seem to work correctly with python 3.9.1 and Fedora-33, in the sense that it automatically does a user-install when the global site-packages is not writeable.

Before installing the ibm_db module run `python -m pip install --upgrade pip`.

My hostname already had python3-dev installed globally.

Notice the pip message **"Defaulting to user installation because normal site-packages is not writeable"**

Then `pip install ibm_db` puts the the CHANGES,LICENSE,README.me, config.py.sample files into the ~/.local/lib/python3.9/site-packages tree

See below:
```

[user3@myhost ~]$ python3 -V
Python 3.9.1


[user3@myhost ~]$ pip -V
pip 20.2.2 from /usr/lib/python3.9/site-packages/pip (python 3.9)


[user3@myhost ~]$ python -m pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable
Collecting pip
  Downloading pip-21.0.1-py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 3.8 MB/s 
Installing collected packages: pip
Successfully installed pip-21.0.1
[user3@myhost ~]$ 


[user3@myhost ~]$ pip install wheel
Defaulting to user installation because normal site-packages is not writeable
Collecting wheel
  Downloading wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel
Successfully installed wheel-0.36.2
[user3@myhost ~]$ 



[user3@myhost ~]$ pip install ibm_db
Defaulting to user installation because normal site-packages is not writeable
Collecting ibm_db
  Using cached ibm_db-3.0.3.tar.gz (794 kB)
Building wheels for collected packages: ibm-db
  Building wheel for ibm-db (setup.py) ... done
  Created wheel for ibm-db: filename=ibm_db-3.0.3-cp39-cp39-linux_x86_64.whl size=41029825 sha256=0922a251883eac03089684f4ba5f0f8ddf1d377cde22c6b4b5546275d7a28a55
  Stored in directory: /home/user3/.cache/pip/wheels/84/08/11/27abc0dfb8fa0866758a63bd899b5f501e6ba21199b3b265a4
Successfully built ibm-db
Installing collected packages: ibm-db
Successfully installed ibm-db-3.0.3
[user3@myhost ~]$ 




[user3@myhost ~]$ pip uninstall ibm_db
Found existing installation: ibm-db 3.0.3
Uninstalling ibm-db-3.0.3:
  Would remove:
    /home/user3/.local/lib/python3.9/site-packages/certs/*
    /home/user3/.local/lib/python3.9/site-packages/clidriver/*
    /home/user3/.local/lib/python3.9/site-packages/ibm_db-3.0.3.dist-info/*
    /home/user3/.local/lib/python3.9/site-packages/ibm_db.cpython-39-x86_64-linux-gnu.so
    /home/user3/.local/lib/python3.9/site-packages/ibm_db_dbi.py
    /home/user3/.local/lib/python3.9/site-packages/ibm_db_tests/*
    /home/user3/.local/lib/python3.9/site-packages/testfunctions.py
    /home/user3/.local/lib/python3.9/site-packages/tests.py
    /home/user3/.local/lib/python3.9/site-packages/usr/lib/python3.9/site-packages/CHANGES
    /home/user3/.local/lib/python3.9/site-packages/usr/lib/python3.9/site-packages/LICENSE
    /home/user3/.local/lib/python3.9/site-packages/usr/lib/python3.9/site-packages/README.md
    /home/user3/.local/lib/python3.9/site-packages/usr/lib/python3.9/site-packages/config.py.sample
Proceed (y/n)? 










```
