### ISSUE TITLE
UnicodeDecodeError in ibm_db.conn_errormsg on z/OS

### ISSUE THREAD

**Issue by kenjaninja** [ibmdb/python-ibmdb#649]
On z/OS, when `ibm_db.connect` is run with incorrect parameters on z/OS, `ibm_db.conn_errormsg` encounters a `UnicodeDecodeError`:
```
import ibm_db

conn = None
try:
        conn = ibm_db.connect('WRONG','','')
except:
        pass

db_error_msg = ibm_db.conn_errormsg()  # Error occurs here
print(db_error_msg)
```
Output:
```
Traceback (most recent call last):
  File "issue.py", line 9, in <module>
    db_error_msg = ibm_db.conn_errormsg()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 0: ordinal not in range(128)
```

Resolving this error to allow for the error message to return would make debugging scripts easier on z/OS.

**Comment by amukherjee28** [comment]
Hi @kenjaninja 

Could you please provide the details of the odbc.ini file used to run the program.

**Comment by kenjaninja** [comment]
here are the contents of the odbc.ini file:
```
[COMMON]
MVSDEFAULTSSID=DSNA1
CONNECTTYPE=1
MULTICONTEXT=2
CURRENTAPPENSCH=ASCII
FLOAT=IEEE

[DSNA1]
MVSATTACHTYPE=RRSAF
PLANNAME=DSNACLI

[DSNA1]
AUTOCOMMIT=1
CURSORHOLD=1
```

**Comment by bimalkjha** [comment]
@kenjaninja Are you still facing this issue? Please check the solutions shared [here](https://stackoverflow.com/questions/18649512/unicodedecodeerror-ascii-codec-cant-decode-byte-0xe2-in-position-13-ordinal) for similar issue. Thanks.

**Comment by kenjaninja** [comment]
@bimalkjha Hi, we are trying to update ibm-db on our z/OS UNIX system to 3.1.0 to check but we are having some XLC problems to resolve on our side. Will get back to you when we resolve the issue.

**Comment by kenjaninja** [comment]
@bimalkjha we updated to ibm-db 3.1.0 and we still see the same problem. Also, since the error is happening inside `ibm_db.conn_errormsg()`, we cannot apply the Stackoverflow solution you linked.

**Comment by amukherjee28** [comment]
@kenjaninja 

I was finally able to reproduce this exact issue and could catch hold of one thing that was different in working and non working case.

The tagging of the ODBC ini file plays an important role in here.

Can you please run the following command and check the tagging of your ODBC ini file.

chtag -p <ODBC.ini file name>

in case it is something like this

```
bash-4.3$ chtag -p ISSUE1.ini
- untagged    T=off ISSUE1.ini
```

Now try and change the tagging to binary

chtag -b <odbc.ini file name>

This shall change the file tagging

```
bash-4.3$ chtag -p ISSUE1.ini
b binary      T=off ISSUE1.ini
```

Once you are done changing the tagging of the file please check again.
This should resolve the issue and the same worked for me.

**Comment by kenjaninja** [comment]
When I set the ini file to binary, it does stop the `ibm_db.conn_errormsg()` unicode error message, but only because it causes an ODBC driver error and breaks valid connections as well:
```python
import ibm_db

conn = None
try:
        conn = ibm_db.connect('','','')
except Exception as e:
        print(e)
        conn_errormsg = ibm_db.conn_errormsg()

if conn:
    stmt = ibm_db.exec_immediate(conn,"SELECT CURRENT MEMBER FROM SYSIBM.SYSDUMMY1")
    if stmt:
        while (ibm_db.fetch_row(stmt)):
            member = ibm_db.result(stmt, 0)
            print("I am on :",member)
    else:
        print(ibm_db.stmt_errormsg())
    ibm_db.close(conn)
else:
    print("No connection)

```
Output:
```
 {DB2 FOR OS/390}{ODBC DRIVER}  SQLSTATE=58004  ERRLOC=2:56:9  CAF "CONNECT" failed using DB2 system:DSNL  RC=0c and REASON=00f30006 SQLCODE=-99999
No connection
 ```

If I run `chtag -r <odbc.ini file name>` to remove the tag I get a proper connection and proper output:
```
I am on : DL71
```

**Comment by amukherjee28** [comment]
Is this resolved with the new release 3.1.1?

**Comment by kenjaninja** [comment]
I cannot check due to not being able to install 3.1.1, caused by #707

**Comment by amukherjee28** [comment]
Closing this issue. In the new release 3.1.1 Unicode character issue has been fixed. Please check with the latest version.
In case the issue persists please open a new issue.

**Comment by mika-data** [comment]
still an issue with 3.1.4

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
>>> import ibm_db_dbi
>>> print(ibm_db.__version__)
3.1.4
>>> con_str = 'DATABASE=TESTDB;HOSTNAME=20.105.248.155;PORT=50000;PROTOCOL=TCPIP;UID=kfw_ocr;PWD=mysupersecretpassword''
>>> ibm_db_conn = ibm_db.connect(con_str, '', '')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Exception
>>> ibm_db.conn_errormsg()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdc in position 204: ordinal not in range(128)
>>>
