### ISSUE TITLE
SQL1598N issue when attempt to connect to database server

### ISSUE THREAD

**Issue by millie-test** [ibmdb/python-ibmdb#665]
After installed ibm_db, SQL1598N error happened when attempt to connect to database server. Error message is as below:
SQLCODE=-1598M][CLI Driver] SQL1598N An attempt to connect to the database server failed because of a licensing problem. SQLSTATE=42968
Anyone knows how to resolve the issue? thanks a lot.

**Comment by amukherjee28** [comment]
Hi @millie-test 

In order to connect to Z/OS and IBM I using the python ibm_db driver db2 license is required for establishing a connecting.
This license has to be obtained only for ZOS and IBM I connections.

The license file need to put into the license folder of the clidriver which comes along with the ibm_db driver installation.

Once you have the proper license file placed the above error can be resolved.

If you are using the default clidriver you need to have the license acquired for db2_v115m6fp0 version.

In case you are using  a different clidriver using IBM_DB_HOME path then please have the license for the version you are using and continue.

Thanks.

**Comment by bchoudhary6415** [comment]
Hello @jason-hobbs 
Since you have installed the license file here: /home/user/.local/lib/python3.8/site-packages/clidriver/license
so add dll directory to this path
import os
os.add_dll_directory('//home//user//.local//lib//python3.8//site-packages//clidriver//bin')

Also you can refer the issue https://github.com/ibmdb/python-ibmdb/issues/899

Thank you

**Comment by jason-hobbs** [comment]
I am on Linux so tried to add the directories to LD_LIBRARY_PATH and PATH to no avail.  My db2cli comes back with a valid license though:

```
===============================================================================
Client information for the current copy:
===============================================================================

Client Package Type       : IBM DB2 Connect Server
Client Version (level/bit): DB2 v11.1.0.0 (s1606081100/64-bit)
Client Platform           : Linux/X8664
Install/Instance Path     : /opt/ibm/db2/V11.1
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path      : /home/db2inst1/sqllib/cfg/db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           : /home/db2inst1/sqllib/cfg/db2cli.ini
db2diag.log Path          : /home/db2inst1/sqllib/db2dump/db2diag.log

===============================================================================
db2dsdriver.cfg schema validation for the entire file:
===============================================================================

Note: The validation utility could not find the configuration file 
db2dsdriver.cfg. The file is searched at 
"/home/db2inst1/sqllib/cfg/db2dsdriver.cfg".

===============================================================================
db2cli.ini validation for database "dbname:host:port":
===============================================================================

Note: The validation utility could not find the configuration file db2cli.ini. 
The file is searched at "/home/db2inst1/sqllib/cfg/db2cli.ini".

===============================================================================
db2dsdriver.cfg validation for database "dbname:host:port":
===============================================================================

Note: The validation utility could not find the configuration file 
db2dsdriver.cfg. The file is searched at 
"/home/db2inst1/sqllib/cfg/db2dsdriver.cfg".

===============================================================================
Connection attempt for database "dbname:host:port":
===============================================================================

[SUCCESS]

===============================================================================

Valid License Found            : Yes
License location               : Client
Server routine type attempted  : SP and UDF
DB2 connect license version    : N/A
===============================================================================
The validation is completed.
===============================================================================
```

**Comment by bimalkjha** [comment]
@jason-hobbs If you want to use your installed Db2 Connect Server with ibm_db, then you need to run below commands from terminal:
```
export IBM_DB_HOME=/home/db2inst1/sqllib
pip install ibm_db --no-binary :all: --no-cache-dir
```
Above installation should fix the issue.

Note that if you are installing ibm_db using `pip install ibm_db`, it will get installed with precompile wheel package which comes with its own clidriver which get installed at `/home/user/.local/lib/python3.8/site-packages/clidriver`. This clidriver is of Db2 V11.5.8 version which requires Db2 Connect V11.5 license. You currently have V11.1 license which will not work with `/home/user/.local/lib/python3.8/site-packages/clidriver`. So, use above commands from terminal. Thanks.

**Comment by jason-hobbs** [comment]
Installing ibm_db like above errors stating:
ERROR: Could not build wheels for ibm-db which use PEP 517 and cannot be installed directly

**Comment by bimalkjha** [comment]
@jason-hobbs Please share complete output of the install command. Thanks.

**Comment by jason-hobbs** [comment]
Well, today with no changes it installed fine.
```
/usr/bin/pip:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point
Collecting ibm_db
  Downloading ibm_db-3.2.1.tar.gz (210 kB)
     |████████████████████████████████| 210 kB 2.4 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: ibm-db
  Building wheel for ibm-db (PEP 517) ... done
  Created wheel for ibm-db: filename=ibm_db-3.2.1-cp38-cp38-linux_x86_64.whl size=41877280 sha256=3c3fa75ffe47913545954f28527c14b8eee7e251fc228a50bee0b8fb942ca017
  Stored in directory: /tmp/pip-ephem-wheel-cache-7fomwm5p/wheels/9d/48/09/488ce3c7b3e20557553dd2f48dae7206c4c99479dd2652796f
Successfully built ibm-db
Installing collected packages: ibm-db
Successfully installed ibm-db-3.2.1
```

Still get the same licensing problem though.

**Comment by bimalkjha** [comment]
@jason-hobbs The above install output is from `pip install ibm_db` command and not from `pip install ibm_db --no-binary :all: --no-cache-dir` command. We need complete output of `pip install ibm_db --no-binary :all: --no-cache-dir` command that shows the command as well as the end. I do not see which command you executed in above shared output. With partial info, it is difficult to assist.
As I mentioned before, if you are installing using `pip install ibm_db` as above, you need to copy db2connect V11.5 license file under `site_packages/clidriver` directory. Your current license is of V11.1 and hence the error is expected.

For further help, please collect complete output of below commands without leaving any single line and open a new issue for help. This issue is old one and already closed.
```
export IBM_DB_HOME=/home/db2inst1/sqllib
ls /opt/ibm/db2/V11.1
ls /home/db2inst1/sqllib
ls /home/db2inst1/sqllib/license
pip uninstall ibm_db
pip install ibm_db --no-binary :all: --no-cache-dir
python yourTestFile.py
```
Thanks.

**Comment by jason-hobbs** [comment]
Okay I will just install 11.5 and go from there.  Thank you for all your help.
