### ISSUE TITLE
Bug Report: Can't Import ibm_db on Mac: Symbol not found: ___cxa_throw_bad_array_new_length

### ISSUE THREAD

**Issue by dodgerbluee** [ibmdb/python-ibmdb#831]
Found several duplicates that say its been resolved, but I have the latest versions and its still occurring for me. I have an M1 chip but am using Rosetta to use x86_64

- Operating System Name: Ventura 13.2.1
- db2level output from clidriver if in use: 
- Python Version: 11.2
- ibm_db version: 3.1.4
- For non-Windows, output of below commands:
  uname: Darwin
  uname -m: x86_64
- Value of below environment variables if set:
  IBM_DB_HOME: N/A
  PATH: /Users/Greg/.pyenv/shims:/Library/Frameworks/Python.framework/Versions/3.11/bin:/usr/sbin:/sbin:/System/Cryptexes/App/usr/bin:/usr/bin:/opt/apache-maven-3.8.6/bin:/usr/local/apache-ant-1.10.12/bin:/usr/local/bin:/bin:/opt/homebrew/bin
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH: N/A

Steps to Reproduce:

1. Try to run ```import ibm_db```

Error:

    import ibm_db
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ibm_db.cpython-311-darwin.so, 0x0002): Symbol not found: ___cxa_throw_bad_array_new_length
  Referenced from: <855AE640-1BCF-3A61-A65E-58F5490BFF43> /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/clidriver/lib/libdb2.dylib
  Expected in:     <31679759-38DC-357A-95C2-542EA70F295F> /usr/lib/libstdc++.6.dylib

**Comment by bimalkjha** [comment]
@dodgerbluee Have you tried the solution mentioned in those duplicates? For MacOS, having x86_64 gcc8 is a pre-requirement. This error is due to missing gcc library libstdc++.6.dylib in your system. Please install gcc version 8 in your system which should resolve the issue. Thanks.

**Comment by dodgerbluee** [comment]
> @dodgerbluee Have you tried the solution mentioned in those duplicates? For MacOS, having x86_64 gcc8 is a pre-requirement. This error is due to missing gcc library libstdc++.6.dylib in your system. Please install gcc version 8 in your system which should resolve the issue. Thanks.

I tried gcc 12.2.0, is this not sufficient?

**Comment by dodgerbluee** [comment]
So `/usr/local/lib/gcc/12/libstdc++.6.dylib` exists but `/usr/lib/libstdc++.6.dylib` doesn't. Still doesn't work when I set:

`DYLD_LIBRARY_PATH=/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/clidriver/lib:/usr/local/lib/gcc/12`

Am I missing an additional step? @bimalkjha

**Comment by bimalkjha** [comment]
@dodgerbluee Can you copy /usr/local/lib/gcc/12/libstdc++.6.dylib as /usr/lib/libstdc++.6.dylib and try. Thanks.

**Comment by themau1111** [comment]
I have exactly the same specifications, I solved the issue with 
export DYLD_LIBRARY_PATH="/usr/local/Cellar/gcc/12.2.0/lib/gcc/12/:$DYLD_LIBRARY_PATH"
you need to set the path where the file is

**Comment by dodgerbluee** [comment]
```
~/GitDev/inflation-index-api python-poc ❯ python3 lambda-sources/retrieve_item/retrieve_item.py --json_request $test_json
Traceback (most recent call last):
  File "/Users/FHZ4/GitDev/inflation-index-api/lambda-sources/retrieve_item/retrieve_item.py", line 9, in <module>
    import inflation_response_builder
  File "/Users/FHZ4/GitDev/inflation-index-api/lambda-sources/retrieve_item/inflation_response_builder.py", line 2, in <module>
    import database_retriever
  File "/Users/FHZ4/GitDev/inflation-index-api/lambda-sources/retrieve_item/database_retriever.py", line 2, in <module>
    import ibm_db
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ibm_db.cpython-311-darwin.so, 0x0002): Symbol not found: ___cxa_throw_bad_array_new_length
  Referenced from: <855AE640-1BCF-3A61-A65E-58F5490BFF43> /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/clidriver/lib/libdb2.dylib
  Expected in:     <31679759-38DC-357A-95C2-542EA70F295F> /usr/lib/libstdc++.6.dylib
~/GitDev/inflation-index-api python-poc ❯ echo $DYLD_LIBRARY_PATH
/usr/local/Cellar/gcc/12.2.0/lib/gcc/12/:
~/GitDev/inflation-index-api python-poc ❯ ls /usr/local/Cellar/gcc/12.2.0/lib/gcc/12/
gcc                      libatomic.a              libgcc_s.1.dylib         libgomp.1.dylib          libitm.a                 libobjc-gnu.dylib        libssp.0.dylib           libstdc++.6.dylib-gdb.py libubsan.1.dylib
libasan.8.dylib          libatomic.dylib          libgfortran.5.dylib      libgomp.a                libitm.dylib             libquadmath.0.dylib      libssp.a                 libstdc++.a              libubsan.dylib
libasan.dylib            libcc1.0.so              libgfortran.a            libgomp.dylib            libitm.spec              libquadmath.a            libssp.dylib             libstdc++.dylib
libasan_preinit.o        libcc1.so                libgfortran.dylib        libgomp.spec             libobjc-gnu.4.dylib      libquadmath.dylib        libssp_nonshared.a       libstdc++fs.a
libatomic.1.dylib        libgcc_s.1.1.dylib       libgfortran.spec         libitm.1.dylib           libobjc-gnu.a            libsanitizer.spec        libstdc++.6.dylib        libsupc++.a
```

Gives me the same error, even after uninstalling ibm_db and reinstalling.

**Comment by dodgerbluee** [comment]
`~/GitDev/script python-poc ❯ python3 lambda-sources/retrieve_item/retrieve_item.py --json_request $test_json
Traceback (most recent call last):
  File "/Users/User/GitDev/script/lambda-sources/retrieve_item/retrieve_item.py", line 9, in <module>
    import builder
  File "/Users/User/GitDev/script/lambda-sources/retrieve_item/builder.py", line 2, in <module>
    import database_retriever
  File "/Users/User/GitDev/script/lambda-sources/retrieve_item/database_retriever.py", line 2, in <module>
    import ibm_db
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ibm_db.cpython-311-darwin.so, 0x0002): Symbol not found: ___cxa_throw_bad_array_new_length
  Referenced from: <855AE640-1BCF-3A61-A65E-58F5490BFF43> /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/clidriver/lib/libdb2.dylib
  Expected in:     <31679759-38DC-357A-95C2-542EA70F295F> /usr/lib/libstdc++.6.dylib
~/GitDev/script python-poc ❯ echo $DYLD_LIBRARY_PATH
/usr/local/Cellar/gcc/12.2.0/lib/gcc/12/:
~/GitDev/script python-poc ❯ ls /usr/local/Cellar/gcc/12.2.0/lib/gcc/12/
gcc                      libatomic.a              libgcc_s.1.dylib         libgomp.1.dylib          libitm.a                 libobjc-gnu.dylib        libssp.0.dylib           libstdc++.6.dylib-gdb.py libubsan.1.dylib
libasan.8.dylib          libatomic.dylib          libgfortran.5.dylib      libgomp.a                libitm.dylib             libquadmath.0.dylib      libssp.a                 libstdc++.a              libubsan.dylib
libasan.dylib            libcc1.0.so              libgfortran.a            libgomp.dylib            libitm.spec              libquadmath.a            libssp.dylib             libstdc++.dylib
libasan_preinit.o        libcc1.so                libgfortran.dylib        libgomp.spec             libobjc-gnu.4.dylib      libquadmath.dylib        libssp_nonshared.a       libstdc++fs.a
libatomic.1.dylib        libgcc_s.1.1.dylib       libgfortran.spec         libitm.1.dylib           libobjc-gnu.a            libsanitizer.spec        libstdc++.6.dylib        libsupc++.a`

Same error with this set. @themau1111

**Comment by themau1111** [comment]
Expected in:     <31679759-38DC-357A-95C2-542EA70F295F> /usr/lib/libstdc++.6.dylib

it is still expecting the file on this path: /usr/lib/libstdc++.6.dylib
I think that the set of env variable did not work properly

**Comment by dodgerbluee** [comment]
> 

Can you tell me what is in your DYLD_LIBRARY_PATH?

Mine only has the gcc path

**Comment by themau1111** [comment]
echo $DYLD_LIBRARY_PATH

/usr/local/Cellar/gcc/12.2.0/lib/gcc/12/:/usr/local/lib/python3.5/site-packages/clidriver/lib:/lib:/usr/local/Cellar/gcc/11.2.0_1/lib/gcc/11:/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/clidriver/lib

I have python 2.7 and 3.9, seems it took 2.7

**Comment by bimalkjha** [comment]
@dodgerbluee  Please set below environment variables:
```
export DYLD_LIBRARY_PATH=/usr/local/Cellar/gcc/12.2.0/lib/gcc/12:/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/clidriver/lib
export PATH=/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/clidriver/bin:$PATH
```

It it sill do not work, then please share output of below commands:
```
ls /usr/local/lib/gcc
ls -l /usr/local/Cellar/gcc/12.2.0/lib/gcc/12/libstdc*
ls -l /usr/lib/libstd*
db2level
ls -l /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/clidriver/lib
gcc -v
```
Thanks.

**Comment by themau1111** [comment]
12	current
lrwxr-xr-x@ 1 mauricio  admin  28 Aug 19  2022 /usr/local/Cellar/gcc/12.2.0/lib/gcc/12/libstdc++.6.dylib -> ../current/libstdc++.6.dylib
lrwxr-xr-x@ 1 mauricio  admin  35 Aug 19  2022 /usr/local/Cellar/gcc/12.2.0/lib/gcc/12/libstdc++.6.dylib-gdb.py -> ../current/libstdc++.6.dylib-gdb.py
lrwxr-xr-x@ 1 mauricio  admin  22 Aug 19  2022 /usr/local/Cellar/gcc/12.2.0/lib/gcc/12/libstdc++.a -> ../current/libstdc++.a
lrwxr-xr-x@ 1 mauricio  admin  26 Aug 19  2022 /usr/local/Cellar/gcc/12.2.0/lib/gcc/12/libstdc++.dylib -> ../current/libstdc++.dylib
lrwxr-xr-x@ 1 mauricio  admin  24 Aug 19  2022 /usr/local/Cellar/gcc/12.2.0/lib/gcc/12/libstdc++fs.a -> ../current/libstdc++fs.a
zsh: no matches found: /usr/lib/libstd*
zsh: command not found: db2level
ls: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/clidriver/lib: No such file or directory
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

also you need xcode fully installed from store, not only command line

**Comment by bimalkjha** [comment]
@themau1111 Thanks for sharing the command output. The `ls /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/clidriver/lib` command has failed. Do you have ibm_db related files under `/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages`? It seems ibm_db is not installed for python3. Please try below commands:
```
pip3 uninstall ibm_db
pip3 install ibm_db
python3
> import ibm_db
```
Thanks.

**Comment by bimalkjha** [comment]
@themau1111 I hope the issue got resolved for you. We have not heard anything in past 10 days. Let me know if we can close this issue. Thanks.

**Comment by svfen** [comment]
I followed the last commands of this thread and even though I ran uninstalled im_db and reinstalled, I get a prompt that im_db isn't installed.

**Comment by bimalkjha** [comment]
@svfen Please follow instructions as documented here: https://github.com/ibmdb/python-ibmdb/blob/master/INSTALL.md#m1chip
